# Generated by Django 3.1.4 on 2020-12-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='request_date',
            field=models.DateTimeField(),
        ),
    ]
